### ISSUE TITLE
Too many values to unpack in detect_markers

### ISSUE THREAD

**Issue by Angeall** [DebVortex/python-ar-markers#1]
I just installed and get this error when I launch the livetest

Traceback (most recent call last):
  File "ar_markers_livetest", line 15, in <module>
    markers = detect_markers(frame)
  File "build\bdist.win32\egg\ar_markers\hamming\detect.py", line 48, in detect_markers
ValueError: too many values to unpack

**Comment by Angeall** [comment]
Ok, this is probably caused by a newer version of openCV

**Comment by Angeall** [comment]
Created pull request to fix it

**Comment by DebVortex** [comment]
Thanks a lot!

I just merged your pullrequest. However, I haven't expected that anyone would ever take a look at this repository. It was merely a short experiment to test OpenCV a bit and remind me how haming code works.

I hope the project helped you in any way.
