### ISSUE TITLE
Can't link the url of blogpost

### ISSUE THREAD

**Issue by BryceQing** [DebVortex/python-ar-markers#6]
![image](https://user-images.githubusercontent.com/41096251/49376479-5aea3200-f742-11e8-80f1-9c134632a7af.png)
As you see, i can't find the resource of "this",can you update the link to resolve this problem.Thanks

**Comment by DebVortex** [comment]
The website of the blogpost / the blogpost itself is no longer available.

However, thanks to the web archive we can get an older version of the page: https://web.archive.org/web/20180104190717/http://iplimage.com/blog/approach-encodedecode-black-white-marker/

Hope that helps. I will update the Link in the README as well.
